export type ComponentMeta = {
  slug: string
  name: string
  description: string
  category: string
  variants?: string[]
}

export const components: ComponentMeta[] = [
  // Layout
  { slug: "aspect-ratio", name: "Aspect Ratio", category: "Layout",
    description: "Displays content within a desired ratio." },
  { slug: "resizable", name: "Resizable", category: "Layout",
    description: "Accessible resizable panel groups and layouts." },
  { slug: "scroll-area", name: "Scroll Area", category: "Layout",
    description: "Augments native scroll functionality for custom styling." },
  { slug: "separator", name: "Separator", category: "Layout",
    description: "Visually or semantically separates content." },
  { slug: "sidebar", name: "Sidebar", category: "Layout",
    description: "A composable, themeable sidebar component." },

  // Typography & Display
  { slug: "typography", name: "Typography", category: "Typography",
    description: "Styles for headings, paragraphs, lists and more." },
  { slug: "badge", name: "Badge", category: "Typography",
    description: "Displays a badge or label.",
    variants: ["default","secondary","destructive","outline"] },
  { slug: "alert", name: "Alert", category: "Typography",
    description: "Displays a callout for user attention.",
    variants: ["default","destructive"] },
  { slug: "label", name: "Label", category: "Typography",
    description: "Renders an accessible label for form controls." },
  { slug: "kbd", name: "Kbd", category: "Typography",
    description: "Displays keyboard shortcut keys." },

  // Forms & Inputs
  { slug: "button", name: "Button", category: "Forms & Inputs",
    description: "Triggers an action or event.",
    variants: ["default","secondary","destructive","outline","ghost","link"] },
  { slug: "button-group", name: "Button Group", category: "Forms & Inputs",
    description: "Groups multiple buttons together." },
  { slug: "input", name: "Input", category: "Forms & Inputs",
    description: "Displays a form input field.",
    variants: ["default","disabled","with label","with error"] },
  { slug: "input-group", name: "Input Group", category: "Forms & Inputs",
    description: "Combines input with addons or icons." },
  { slug: "input-otp", name: "Input OTP", category: "Forms & Inputs",
    description: "Accessible one-time password input." },
  { slug: "textarea", name: "Textarea", category: "Forms & Inputs",
    description: "Displays a multi-line text input." },
  { slug: "checkbox", name: "Checkbox", category: "Forms & Inputs",
    description: "A control that allows the user to toggle between states." },
  { slug: "radio-group", name: "Radio Group", category: "Forms & Inputs",
    description: "A set of radio buttons for single selection." },
  { slug: "select", name: "Select", category: "Forms & Inputs",
    description: "Displays a list of options for the user to pick from." },
  { slug: "native-select", name: "Native Select", category: "Forms & Inputs",
    description: "A native HTML select element with styling." },
  { slug: "switch", name: "Switch", category: "Forms & Inputs",
    description: "A control that allows toggling between checked states." },
  { slug: "slider", name: "Slider", category: "Forms & Inputs",
    description: "An input where the user selects from a range of values." },
  { slug: "toggle", name: "Toggle", category: "Forms & Inputs",
    description: "A two-state button that can be on or off." },
  { slug: "toggle-group", name: "Toggle Group", category: "Forms & Inputs",
    description: "A set of two-state buttons that can be toggled." },
  { slug: "calendar", name: "Calendar", category: "Forms & Inputs",
    description: "A date field component for selecting dates." },
  { slug: "date-picker", name: "Date Picker", category: "Forms & Inputs",
    description: "A date picker with range and presets." },
  { slug: "combobox", name: "Combobox", category: "Forms & Inputs",
    description: "Autocomplete input and command palette." },
  { slug: "field", name: "Field", category: "Forms & Inputs",
    description: "A form field wrapper with label and validation." },
  { slug: "form-layouts", name: "Form Layouts", category: "Forms & Inputs",
    description: "Production form compositions for registration, settings, and plan selection flows." },

  // Navigation
  { slug: "breadcrumb", name: "Breadcrumb", category: "Navigation",
    description: "Displays the path to the current resource." },
  { slug: "navigation-menu", name: "Navigation Menu", category: "Navigation",
    description: "A collection of links for navigating websites." },
  { slug: "menubar", name: "Menubar", category: "Navigation",
    description: "A menu bar for desktop applications." },
  { slug: "pagination", name: "Pagination", category: "Navigation",
    description: "Pagination with page navigation and previous/next links." },
  { slug: "tabs", name: "Tabs", category: "Navigation",
    description: "A set of layered sections of content.",
    variants: ["default"] },

  // Overlays & Feedback
  { slug: "dialog", name: "Dialog", category: "Overlays & Feedback",
    description: "A window overlaid on the primary window." },
  { slug: "alert-dialog", name: "Alert Dialog", category: "Overlays & Feedback",
    description: "A modal dialog that interrupts the user with important content." },
  { slug: "drawer", name: "Drawer", category: "Overlays & Feedback",
    description: "A panel that slides in from the edge of the screen." },
  { slug: "sheet", name: "Sheet", category: "Overlays & Feedback",
    description: "Extends the Dialog component to display from screen edges." },
  { slug: "popover", name: "Popover", category: "Overlays & Feedback",
    description: "Displays rich content in a portal, triggered by a button." },
  { slug: "hover-card", name: "Hover Card", category: "Overlays & Feedback",
    description: "Preview content available behind a link." },
  { slug: "context-menu", name: "Context Menu", category: "Overlays & Feedback",
    description: "Displays a menu to the user — triggered by a right click." },
  { slug: "dropdown-menu", name: "Dropdown Menu", category: "Overlays & Feedback",
    description: "Displays a menu when triggered by a button." },
  { slug: "tooltip", name: "Tooltip", category: "Overlays & Feedback",
    description: "A popup that displays information related to an element." },
  { slug: "toast", name: "Toast", category: "Overlays & Feedback",
    description: "A succinct message that is displayed temporarily." },
  { slug: "sonner", name: "Sonner", category: "Overlays & Feedback",
    description: "An opinionated toast component for React." },

  // Data Display
  { slug: "card", name: "Card", category: "Data Display",
    description: "Displays a card with header, content, and footer." },
  { slug: "table", name: "Table", category: "Data Display",
    description: "A responsive table component." },
  { slug: "data-table", name: "Data Table", category: "Data Display",
    description: "Powerful table with sorting, filtering, and pagination." },
  { slug: "avatar", name: "Avatar", category: "Data Display",
    description: "An image element with a fallback for representing a user." },
  { slug: "progress", name: "Progress", category: "Data Display",
    description: "Displays an indicator showing task completion progress." },
  { slug: "spinner", name: "Spinner", category: "Data Display",
    description: "A loading spinner indicator." },
  { slug: "skeleton", name: "Skeleton", category: "Data Display",
    description: "Use to show a placeholder while content is loading." },
  { slug: "chart", name: "Chart", category: "Data Display",
    description: "Beautiful charts built with Recharts." },
  { slug: "carousel", name: "Carousel", category: "Data Display",
    description: "A carousel with motion and swipe support." },
  { slug: "empty", name: "Empty", category: "Data Display",
    description: "An empty state component." },

  // Utilities
  { slug: "accordion", name: "Accordion", category: "Utilities",
    description: "Vertically stacked interactive headings that reveal content." },
  { slug: "collapsible", name: "Collapsible", category: "Utilities",
    description: "An interactive component that expands and collapses content." },
  { slug: "command", name: "Command", category: "Utilities",
    description: "Fast, composable, unstyled command menu for React." },
  { slug: "item", name: "Item", category: "Utilities",
    description: "A generic item component for lists and menus." },
  { slug: "direction", name: "Direction", category: "Utilities",
    description: "Wraps your app to provide RTL/LTR direction context." },

  // Metrics & Feeds
  { slug: "avatar-group", name: "Avatar Group", category: "Metrics & Feeds",
    description: "Overlapping avatar stack with overflow count." },
  { slug: "stat-card", name: "Stat Card", category: "Metrics & Feeds",
    description: "KPI card with trend indicator and optional icon." },
  { slug: "activity-feed", name: "Activity Feed", category: "Metrics & Feeds",
    description: "Chronological list of user actions with avatars." },
  { slug: "timeline", name: "Timeline", category: "Metrics & Feeds",
    description: "Vertical approval or event timeline with status indicators." },
  { slug: "metric-panels", name: "Metric Panels", category: "Metrics & Feeds",
    description: "Composed metric panels for KPI rows, usage dashboards, quota tracking, and trend summaries." },

  // Planning
  { slug: "stepper", name: "Stepper", category: "Planning",
    description: "Multi-step progress indicator with horizontal and vertical variants." },
  { slug: "kanban-board", name: "Kanban Board", category: "Planning",
    description: "Drag-and-drop Kanban board with column management." },
  { slug: "gantt", name: "Gantt", category: "Planning",
    description: "Gantt timeline chart for project phase planning." },

  // Application Primitives
  { slug: "id-chip", name: "ID Chip", category: "Application Primitives",
    description: "Monospace reference chip for IDs like EPIC-014 or RISK-01." },
  { slug: "linked-chip", name: "Linked Chip", category: "Application Primitives",
    description: "Clickable chip with type icon for linking to domain objects." },
  { slug: "health-indicator", name: "Health Indicator", category: "Application Primitives",
    description: "Semantic status icon for healthy, warning, or error states." },
  { slug: "readiness-item", name: "Readiness Item", category: "Application Primitives",
    description: "Display-only checklist row with pass, warning, or fail status." },
  { slug: "stepper-counter", name: "Stepper Counter", category: "Application Primitives",
    description: "Inline stage progress counter with mini progress bar." },
  { slug: "l1-distribution-bar", name: "L1 Distribution Bar", category: "Application Primitives",
    description: "Segmented bar showing Experience, Workflow, Integration, Foundation split." },

  // AI Features
  { slug: "ai-action-bar", name: "AI Action Bar", category: "AI Features",
    description: "Subtle action strip with Sparkles icon and AI-powered action links." },
  { slug: "ai-draft-state", name: "AI Draft State", category: "AI Features",
    description: "Three-state badge strip for AI Draft → Reviewed → Approved flow." },
  { slug: "ai-suggestion-card", name: "AI Suggestion Card", category: "AI Features",
    description: "Compact card for AI suggestions with Apply and Dismiss actions." },

  // Extended UI
  { slug: "compact-button", name: "Compact Button", category: "Extended UI",
    description: "Icon-only square button for constrained layouts, with stroke, ghost, and white variants." },
  { slug: "link-button", name: "Link Button", category: "Extended UI",
    description: "Text-only inline link button with underline decoration in gray, primary, and error variants." },
  { slug: "banner", name: "Banner", category: "Extended UI",
    description: "Full-width announcement bar with filled, light, and stroke variants across 5 status types." },
  { slug: "progress-circle", name: "Progress Circle", category: "Extended UI",
    description: "SVG circular progress ring with optional centered content slot." },
  { slug: "status-badge", name: "Status Badge", category: "Extended UI",
    description: "Compact semantic status indicator for completed, pending, failed, and disabled states." },
  { slug: "tag", name: "Tag", category: "Extended UI",
    description: "Dismissible categorization label with optional icon in stroke and gray variants." },
  { slug: "hint", name: "Hint", category: "Extended UI",
    description: "Helper or error text displayed beneath form inputs, with optional icon." },
  { slug: "segmented-control", name: "Segmented Control", category: "Extended UI",
    description: "Animated pill-background tab switcher built on Radix Tabs." },
  { slug: "tab-menu-horizontal", name: "Tab Menu Horizontal", category: "Extended UI",
    description: "Scrollable horizontal tab navigation with animated underline indicator." },
  { slug: "tab-menu-vertical", name: "Tab Menu Vertical", category: "Extended UI",
    description: "Vertical stacked navigation tabs with icon, label, and active arrow." },
  { slug: "dot-stepper", name: "Dot Stepper", category: "Extended UI",
    description: "Minimal circular dot progress indicator for carousels and wizards." },
  { slug: "horizontal-stepper", name: "Horizontal Stepper", category: "Extended UI",
    description: "Sequential numbered step indicator with separator arrows and completed checkmarks." },
  { slug: "vertical-stepper", name: "Vertical Stepper", category: "Extended UI",
    description: "Vertical step indicator with connector lines and optional descriptions." },
  { slug: "rating", name: "Rating", category: "Extended UI",
    description: "Interactive star or heart rating with read-only and hover states." },
  { slug: "file-upload", name: "File Upload", category: "Extended UI",
    description: "Drag-and-drop file upload zone with drag-over highlight state." },
  { slug: "notification", name: "Notification", category: "Extended UI",
    description: "Positioned notification card with status icon, title, description, and optional action." },
  { slug: "avatar-group-compact", name: "Avatar Group Compact", category: "Extended UI",
    description: "Compact overlapping avatar stack with overflow chip and size variants." },

  // Application Components
  { slug: "section-document-card", name: "Section Document Card", category: "Application Components",
    description: "Document section card with status badge, edit button, and AI action bar." },
  { slug: "l1-component-card", name: "L1 Component Card", category: "Application Components",
    description: "Domain model card for an L1 solution component with health and epics." },
  { slug: "epic-card", name: "Epic Card", category: "Application Components",
    description: "Kanban card for an epic with ID chip, status badge, and conflict indicator." },
  { slug: "phase-column-header", name: "Phase Column Header", category: "Application Components",
    description: "Kanban column header with stats and L1 distribution bar." },
  { slug: "risk-heatmap", name: "Risk Heatmap", category: "Application Components",
    description: "3×3 likelihood × impact grid with colour-coded risk cells." },
  { slug: "open-question-row", name: "Open Question Row", category: "Application Components",
    description: "Full-width row for open questions with linked items and action buttons." },
  { slug: "approval-workflow-card", name: "Approval Workflow Card", category: "Application Components",
    description: "Card embedding an approval timeline with Approve/Request Changes buttons." },
  { slug: "review-checklist-row", name: "Review Checklist Row", category: "Application Components",
    description: "Checklist row with status icon, reviewer avatar, and status dropdown." },
  { slug: "output-card", name: "Output Card", category: "Application Components",
    description: "Document output card with format badge, readiness checklist, and action buttons." },
  { slug: "intake-snapshot-card", name: "Intake Snapshot Card", category: "Application Components",
    description: "Compact summary card for intake data with KV pairs and system tags." },
  { slug: "estimation-rollup-tree", name: "Estimation Roll-Up Tree", category: "Application Components",
    description: "Collapsible tree table showing Phase → L1 → L2 → L3 estimate roll-up." },
  { slug: "estimate-detail-drawer", name: "Estimate Detail Drawer", category: "Application Components",
    description: "Sheet drawer showing story estimate breakdown with expert override." },
  { slug: "reconciliation-panel", name: "Reconciliation Panel", category: "Application Components",
    description: "Side-by-side top-down vs bottoms-up reconciliation with decision radio group." },
  { slug: "team-roster-panel", name: "Team Roster Panel", category: "Application Components",
    description: "Tabbed table showing client and Nymbl team roles with phase allocations." },
  { slug: "portfolio-pipeline-view", name: "Portfolio Pipeline View", category: "Application Components",
    description: "Toggle between table and Kanban views for the engagement pipeline." },
  { slug: "app-sidebar", name: "App Sidebar", category: "Application Components",
    description: "Dark app and engagement sidebars for NOS product shells." },
]

export const categories = [
  "Layout",
  "Typography",
  "Forms & Inputs",
  "Navigation",
  "Overlays & Feedback",
  "Data Display",
  "Utilities",
  "Metrics & Feeds",
  "Planning",
  "Application Primitives",
  "AI Features",
  "Extended UI",
  "Application Components",
]
