export type ComponentMeta = {
  slug: string
  name: string
  description: string
  category: string
  variants?: string[]
  /** 1-2 sentence comparative guidance: when to pick this over a sibling. */
  whenToUse?: string
}

export const components: ComponentMeta[] = [
  // Layout
  { slug: "aspect-ratio", name: "Aspect Ratio", category: "Layout",
    description: "Displays content within a desired ratio.",
    whenToUse: "Use to lock media or embeds to a fixed width:height ratio so they scale without layout shift. For freely resizable regions use resizable; for scroll overflow use scroll-area." },
  { slug: "resizable", name: "Resizable", category: "Layout",
    description: "Accessible resizable panel groups and layouts.",
    whenToUse: "Use for user-adjustable split panes such as a sidebar plus content or editor plus preview. For fixed proportional media use aspect-ratio." },
  { slug: "frame", name: "Frame", category: "Layout",
    description: "Composable operational surface for grouped app panels.",
    whenToUse: "Use to compose dashboard panels, review frames, and grouped workflow surfaces with consistent headers, content, and footers. For a single standalone card use card." },
  { slug: "scroll-area", name: "Scroll Area", category: "Layout",
    description: "Augments native scroll functionality for custom styling.",
    whenToUse: "Use to give an overflowing region a styled, cross-browser scrollbar instead of raw overflow when the scrollbar must match the design." },
  { slug: "separator", name: "Separator", category: "Layout",
    description: "Visually or semantically separates content.",
    whenToUse: "Use to divide related groups of content or controls with a thin rule. For labelled section breaks use a heading; for spacing alone use layout gaps." },
  { slug: "sidebar", name: "Sidebar", category: "Layout",
    description: "A composable, themeable sidebar component.",
    whenToUse: "Use as the composable shell for app-level navigation. In Nymbl apps prefer the prebuilt app-sidebar block, which wraps this with NOS styling." },
  { slug: "direction", name: "Direction", category: "Layout",
    description: "Wraps your app to provide RTL/LTR direction context.",
    whenToUse: "Use once at the app root to provide RTL/LTR context to Radix components. Not needed for left-to-right-only apps." },

  // Typography
  { slug: "typography", name: "Typography", category: "Typography",
    description: "Styles for headings, paragraphs, lists and more.",
    whenToUse: "Use for long-form prose styling such as headings, paragraphs, and lists. For a single inline caption use label; for keyboard keys use kbd." },
  { slug: "label", name: "Label", category: "Typography",
    description: "Renders an accessible label for form controls.",
    whenToUse: "Use to caption a form control and bind it for accessibility. For helper or error text beneath a field use hint; for body prose use typography." },
  { slug: "kbd", name: "Kbd", category: "Typography",
    description: "Displays keyboard shortcut keys.",
    whenToUse: "Use to render keyboard shortcut keys inline. For code or commands use a monospace code style instead." },

  // Buttons & Actions
  { slug: "button", name: "Button", category: "Buttons & Actions",
    description: "Triggers an action or event.",
    variants: ["default","secondary","destructive","outline","ghost","link"],
    whenToUse: "Use for primary and secondary actions with a visible text label. For icon-only actions in tight toolbars use compact-button; for inline text actions use link-button." },
  { slug: "button-group", name: "Button Group", category: "Buttons & Actions",
    description: "Groups multiple buttons together.",
    whenToUse: "Use to join related buttons into a segmented or split button. For mutually exclusive on/off choices use toggle-group." },
  { slug: "compact-button", name: "Compact Button", category: "Buttons & Actions",
    description: "Icon-only square button for constrained layouts, with stroke, ghost, and white variants.",
    whenToUse: "Use for icon-only actions in dense toolbars and table rows where space is constrained. For labelled actions use button; for inline text links use link-button." },
  { slug: "link-button", name: "Link Button", category: "Buttons & Actions",
    description: "Text-only inline link button with underline decoration in gray, primary, and error variants.",
    whenToUse: "Use for low-emphasis inline actions that sit within or beside body text. For standalone CTAs use button; for icon-only controls use compact-button." },
  { slug: "toggle", name: "Toggle", category: "Buttons & Actions",
    description: "A two-state button that can be on or off.",
    whenToUse: "Use for a single button-style on/off control such as bold. For a preference-style setting use switch; for a checked list item use checkbox." },
  { slug: "toggle-group", name: "Toggle Group", category: "Buttons & Actions",
    description: "A set of two-state buttons that can be toggled.",
    whenToUse: "Use for a set of related two-state buttons such as text alignment. For navigating between views use tabs or segmented-control." },

  // Forms & Inputs
  { slug: "input", name: "Input", category: "Forms & Inputs",
    description: "Displays a form input field.",
    variants: ["default","disabled","with label","with error"],
    whenToUse: "Use for single-line free text. For multi-line text use textarea; for addons or icons use input-group; for verification codes use input-otp." },
  { slug: "input-group", name: "Input Group", category: "Forms & Inputs",
    description: "Combines input with addons or icons.",
    whenToUse: "Use to attach icons, prefixes, or buttons to an input. For a plain field use input." },
  { slug: "input-otp", name: "Input OTP", category: "Forms & Inputs",
    description: "Accessible one-time password input.",
    whenToUse: "Use for fixed-length verification codes. For general short text use input." },
  { slug: "textarea", name: "Textarea", category: "Forms & Inputs",
    description: "Displays a multi-line text input.",
    whenToUse: "Use for multi-line free text such as notes or descriptions. For single-line entry use input." },
  { slug: "checkbox", name: "Checkbox", category: "Forms & Inputs",
    description: "A control that allows the user to toggle between states.",
    whenToUse: "Use for independent boolean choices or multi-select lists. For mutually exclusive options use radio-group; for an instant setting use switch." },
  { slug: "radio-group", name: "Radio Group", category: "Forms & Inputs",
    description: "A set of radio buttons for single selection.",
    whenToUse: "Use to pick exactly one option from a small visible set. For many options use select; for two states use switch." },
  { slug: "select", name: "Select", category: "Forms & Inputs",
    description: "Displays a list of options for the user to pick from.",
    whenToUse: "Use to pick one option from a medium-to-long dropdown list. For free-text filtering use combobox; for a small visible set use radio-group; for OS-native behaviour use native-select." },
  { slug: "native-select", name: "Native Select", category: "Forms & Inputs",
    description: "A native HTML select element with styling.",
    whenToUse: "Use when you need the OS-native select control, e.g. simple mobile forms. For richer styling and search use select or combobox." },
  { slug: "switch", name: "Switch", category: "Forms & Inputs",
    description: "A control that allows toggling between checked states.",
    whenToUse: "Use for an instant on/off setting that applies immediately. For choices confirmed on submit use checkbox; for button-style toggles use toggle." },
  { slug: "slider", name: "Slider", category: "Forms & Inputs",
    description: "An input where the user selects from a range of values.",
    whenToUse: "Use to choose a number or range along a continuum where precision is loose. For exact numeric entry use input." },
  { slug: "calendar", name: "Calendar", category: "Forms & Inputs",
    description: "A date field component for selecting dates.",
    whenToUse: "Use to pick a date from an inline month grid. For a compact trigger with presets use date-picker." },
  { slug: "date-picker", name: "Date Picker", category: "Forms & Inputs",
    description: "A date picker with range and presets.",
    whenToUse: "Use for date or range selection from a compact input with presets. For an always-visible grid use calendar." },
  { slug: "date-selector", name: "Date Selector", category: "Forms & Inputs",
    description: "Compact operational period selector for days, months, quarters, half-years, and years.",
    whenToUse: "Use for reporting, planning, billing, and staffing periods where users choose a period plus operator. For a simple calendar date use date-picker." },
  { slug: "combobox", name: "Combobox", category: "Forms & Inputs",
    description: "Autocomplete input and command palette.",
    whenToUse: "Use for searchable single-select with free-text filtering. For a plain list use select; for a global action launcher use command." },
  { slug: "entity-picker", name: "Entity Picker", category: "Forms & Inputs",
    description: "Opinionated picker for accounts, contacts, projects, people, skills, and roles.",
    whenToUse: "Use when users select NOS domain entities with metadata and status context. For generic option lists use combobox." },
  { slug: "number-field", name: "Number Field", category: "Forms & Inputs",
    description: "A numeric input with increment and decrement controls.",
    whenToUse: "Use for numeric values that benefit from stepper buttons (quantity, price, duration). For unrestricted numeric text use input with type=number; for a range use slider." },
  { slug: "phone-input", name: "Phone Input", category: "Forms & Inputs",
    description: "Phone number input with country and dial-code selector.",
    whenToUse: "Use for Prospect and Engage contact records. For unrelated free text use input." },
  { slug: "field", name: "Field", category: "Forms & Inputs",
    description: "A form field wrapper with label and validation.",
    whenToUse: "Use to wrap a control with its label, description, and error in consistent spacing. For just the caption use label; for standalone helper text use hint." },
  { slug: "file-upload", name: "File Upload", category: "Forms & Inputs",
    description: "Drag-and-drop file upload zone with drag-over highlight state.",
    whenToUse: "Use for drag-and-drop or click file selection. Prefer this styled zone over a plain file input." },
  { slug: "rating", name: "Rating", category: "Forms & Inputs",
    description: "Interactive star or heart rating with read-only and hover states.",
    whenToUse: "Use to capture or display a star or heart score. For progress toward completion use progress; for status use status-badge." },
  { slug: "form-layouts", name: "Form Layouts", category: "Forms & Inputs",
    description: "Production form compositions for registration, settings, and plan selection flows.",
    whenToUse: "Use as a reference for composing full forms from field, input, and card. Copy the pattern rather than treating it as one component." },

  // Navigation
  { slug: "breadcrumb", name: "Breadcrumb", category: "Navigation",
    description: "Displays the path to the current resource.",
    whenToUse: "Use to show the path to the current page and step back up. For switching between sibling views use tabs or tab-menu." },
  { slug: "scrollspy", name: "Scrollspy", category: "Navigation",
    description: "In-page section navigation for long operational surfaces.",
    whenToUse: "Use for scope docs, proposal builders, long admin pages, and pattern documentation. For page hierarchy use breadcrumb; for switching views use tabs." },
  { slug: "navigation-menu", name: "Navigation Menu", category: "Navigation",
    description: "A collection of links for navigating websites.",
    whenToUse: "Use for top-level site navigation with optional dropdown panels. For in-page section switching use tabs; for desktop app menus use menubar." },
  { slug: "menubar", name: "Menubar", category: "Navigation",
    description: "A menu bar for desktop applications.",
    whenToUse: "Use for desktop-app-style menu bars such as File, Edit, View. For a single trigger menu use dropdown-menu." },
  { slug: "pagination", name: "Pagination", category: "Navigation",
    description: "Pagination with page navigation and previous/next links.",
    whenToUse: "Use to page through large result sets with numbered controls. For incremental loading use a load-more button." },
  { slug: "tabs", name: "Tabs", category: "Navigation",
    description: "A set of layered sections of content.",
    variants: ["default"],
    whenToUse: "Use to switch between equal-weight content panels within a view. For a compact 2-3 option toggle use segmented-control; for page-level section nav use tab-menu-horizontal." },
  { slug: "segmented-control", name: "Segmented Control", category: "Navigation",
    description: "Animated pill-background tab switcher built on Radix Tabs.",
    whenToUse: "Use for a compact 2-4 option toggle with a sliding pill such as a view switch. For many panels use tabs; for page section nav use tab-menu-horizontal." },
  { slug: "tab-menu-horizontal", name: "Tab Menu Horizontal", category: "Navigation",
    description: "Scrollable horizontal tab navigation with animated underline indicator.",
    whenToUse: "Use for page-level section navigation with an underline indicator and optional badges. For switching content panels in place use tabs; for a sidebar list use tab-menu-vertical." },
  { slug: "tab-menu-vertical", name: "Tab Menu Vertical", category: "Navigation",
    description: "Vertical stacked navigation tabs with icon, label, and active arrow.",
    whenToUse: "Use for a stacked left-rail menu with icons such as settings sections. For top navigation use tab-menu-horizontal." },

  // Overlays
  { slug: "dialog", name: "Dialog", category: "Overlays",
    description: "A window overlaid on the primary window.",
    whenToUse: "Use for focused modal tasks that interrupt the flow. For destructive confirmation use alert-dialog; for side panels use sheet or drawer; for anchored content use popover." },
  { slug: "alert-dialog", name: "Alert Dialog", category: "Overlays",
    description: "A modal dialog that interrupts the user with important content.",
    whenToUse: "Use for destructive or irreversible confirmations that require an explicit choice. For non-critical modal content use dialog." },
  { slug: "drawer", name: "Drawer", category: "Overlays",
    description: "A panel that slides in from the edge of the screen.",
    whenToUse: "Use for a mobile-friendly panel that slides from the bottom or edge. For desktop side panels use sheet; for centered modals use dialog." },
  { slug: "sheet", name: "Sheet", category: "Overlays",
    description: "Extends the Dialog component to display from screen edges.",
    whenToUse: "Use for a side panel of supporting content or forms anchored to a screen edge. For bottom mobile panels use drawer; for centered modals use dialog." },
  { slug: "popover", name: "Popover", category: "Overlays",
    description: "Displays rich content in a portal, triggered by a button.",
    whenToUse: "Use for lightweight contextual content anchored to a trigger and dismissed on outside click. For hover-only previews use hover-card; for menus use dropdown-menu." },
  { slug: "hover-card", name: "Hover Card", category: "Overlays",
    description: "Preview content available behind a link.",
    whenToUse: "Use to preview non-interactive content on hover over a link. For click-triggered content use popover." },
  { slug: "context-menu", name: "Context Menu", category: "Overlays",
    description: "Displays a menu to the user — triggered by a right click.",
    whenToUse: "Use for right-click actions on an element. For a button-triggered menu use dropdown-menu." },
  { slug: "dropdown-menu", name: "Dropdown Menu", category: "Overlays",
    description: "Displays a menu when triggered by a button.",
    whenToUse: "Use for a menu of actions opened from a button. For right-click menus use context-menu; for app menu bars use menubar." },
  { slug: "tooltip", name: "Tooltip", category: "Overlays",
    description: "A popup that displays information related to an element.",
    whenToUse: "Use for short, non-essential hints on hover or focus. For interactive content use popover; for persistent status use a badge." },
  { slug: "command", name: "Command", category: "Overlays",
    description: "Fast, composable, unstyled command menu for React.",
    whenToUse: "Use for a searchable command palette or quick action launcher. For inline searchable select use combobox." },

  // Feedback
  { slug: "alert", name: "Alert", category: "Feedback",
    description: "Displays a callout for user attention.",
    variants: ["default","destructive"],
    whenToUse: "Use for an inline, persistent message tied to a region. For a full-width page-top announcement use banner; for transient confirmations use toast; for a positioned card use notification." },
  { slug: "banner", name: "Banner", category: "Feedback",
    description: "Full-width announcement bar with filled, light, and stroke variants across 5 status types.",
    whenToUse: "Use for a full-width announcement across the top of a page or app. For region-scoped messages use alert; for transient toasts use toast." },
  { slug: "toast", name: "Toast", category: "Feedback",
    description: "A succinct message that is displayed temporarily.",
    whenToUse: "Use for brief, auto-dismissing confirmations. For persistent inline messages use alert; for richer positioned cards use notification. Sonner is the preferred implementation." },
  { slug: "sonner", name: "Sonner", category: "Feedback",
    description: "An opinionated toast component for React.",
    whenToUse: "Use as the default toast system for new work. Prefer it over the legacy toast component." },
  { slug: "notification", name: "Notification", category: "Feedback",
    description: "Positioned notification card with status icon, title, description, and optional action.",
    whenToUse: "Use for a positioned status card with title, description, and optional action. For inline page messages use alert; for quick confirmations use toast." },
  { slug: "hint", name: "Hint", category: "Feedback",
    description: "Helper or error text displayed beneath form inputs, with optional icon.",
    whenToUse: "Use for helper or error text beneath a form control. For the control's caption use label; for page-level messages use alert." },
  { slug: "spinner", name: "Spinner", category: "Feedback",
    description: "A loading spinner indicator.",
    whenToUse: "Use for short indeterminate waits on a control or button. For content placeholders use skeleton; for measurable progress use progress." },
  { slug: "skeleton", name: "Skeleton", category: "Feedback",
    description: "Use to show a placeholder while content is loading.",
    whenToUse: "Use to placeholder content layout while data loads, reducing shift. For a simple spinner use spinner." },
  { slug: "empty", name: "Empty", category: "Feedback",
    description: "An empty state component.",
    whenToUse: "Use for empty states with guidance and an action. For loading use skeleton; for errors use alert." },
  { slug: "progress", name: "Progress", category: "Feedback",
    description: "Displays an indicator showing task completion progress.",
    whenToUse: "Use for a linear, determinate progress bar. For a circular ring use progress-circle; for indeterminate waits use spinner." },
  { slug: "progress-circle", name: "Progress Circle", category: "Feedback",
    description: "SVG circular progress ring with optional centered content slot.",
    whenToUse: "Use for compact circular progress, often with a centered value. For linear bars use progress; for step flows use stepper." },

  // Data Display
  { slug: "card", name: "Card", category: "Data Display",
    description: "Displays a card with header, content, and footer.",
    whenToUse: "Use as a surface to group related content and actions. For metrics use stat-card; for dense intake summaries use intake-snapshot-card." },
  { slug: "table", name: "Table", category: "Data Display",
    description: "A responsive table component.",
    whenToUse: "Use for static or lightly interactive tabular data. For sorting, filtering, and pagination use data-table." },
  { slug: "data-table", name: "Data Table", category: "Data Display",
    description: "Powerful table with sorting, filtering, and pagination.",
    whenToUse: "Use for rich tabular data needing sort, filter, selection, and pagination. For simple static rows use table." },
  { slug: "filters", name: "Filters", category: "Data Display",
    description: "Filter chip bar for faceted operational lists and grids.",
    whenToUse: "Use above tables, grids, boards, and dashboards when users need to combine several structured filters. For a single searchable value use input or combobox." },
  { slug: "data-grid", name: "Data Grid", category: "Data Display",
    description: "Dense operational grid with toolbar, selection, column controls, and expanded rows.",
    whenToUse: "Use for high-density operational workspaces that need toolbar controls, column visibility, row selection, and expandable detail rows. For simpler tables use data-table." },
  { slug: "avatar", name: "Avatar", category: "Data Display",
    description: "An image element with a fallback for representing a user.",
    whenToUse: "Use to represent a single user or entity. For a stack of several use avatar-group." },
  { slug: "avatar-group", name: "Avatar Group", category: "Data Display",
    description: "Overlapping avatar stack with overflow count, plus compact and sizing variants.",
    variants: ["default","compact","sm","lg"],
    whenToUse: "Use to show several overlapping avatars with an overflow count; includes a compact variant. For one user use avatar." },
  { slug: "badge", name: "Badge", category: "Data Display",
    description: "Displays a badge or label.",
    variants: ["default","secondary","destructive","outline"],
    whenToUse: "Use for generic counts, labels, and categorisation with a chosen style variant. For semantic process states use status-badge; for dismissible user labels use tag." },
  { slug: "status-badge", name: "Status Badge", category: "Data Display",
    description: "Compact semantic status indicator for completed, pending, failed, and disabled states.",
    whenToUse: "Use for semantic lifecycle states where colour and icon follow the status. For free-form labels use badge; for removable filters use tag." },
  { slug: "tag", name: "Tag", category: "Data Display",
    description: "Dismissible categorization label with optional icon in stroke and gray variants.",
    whenToUse: "Use for dismissible, user-applied labels such as filters or keywords. For non-removable status use status-badge; for static counts use badge." },
  { slug: "id-chip", name: "ID Chip", category: "Data Display",
    description: "Monospace reference chip for IDs like EPIC-014 or RISK-01.",
    whenToUse: "Use for monospace reference IDs. For a clickable link to a domain object use linked-chip." },
  { slug: "linked-chip", name: "Linked Chip", category: "Data Display",
    description: "Clickable chip with type icon for linking to domain objects.",
    whenToUse: "Use for a clickable chip that links to a domain object, with a type icon. For a non-interactive ID use id-chip." },
  { slug: "accordion", name: "Accordion", category: "Data Display",
    description: "Vertically stacked interactive headings that reveal content.",
    whenToUse: "Use to stack multiple independently collapsible sections. For a single show/hide region use collapsible." },
  { slug: "collapsible", name: "Collapsible", category: "Data Display",
    description: "An interactive component that expands and collapses content.",
    whenToUse: "Use to show or hide a single region of content. For multiple stacked sections use accordion." },
  { slug: "tree", name: "Tree", category: "Data Display",
    description: "Expandable hierarchy for scoped work, releases, skills, and nested navigation.",
    whenToUse: "Use for nested structures where hierarchy is the primary thing users need to scan. For tabular hierarchy with many metrics use a data grid or domain-specific roll-up tree." },
  { slug: "item", name: "Item", category: "Data Display",
    description: "A generic item component for lists and menus.",
    whenToUse: "Use as a generic list or menu row with leading and trailing slots. For full data grids use table." },
  { slug: "carousel", name: "Carousel", category: "Data Display",
    description: "A carousel with motion and swipe support.",
    whenToUse: "Use for swipeable horizontal galleries of cards or media. For paged data use pagination." },

  // Data Viz & Metrics
  { slug: "chart", name: "Chart", category: "Data Viz & Metrics",
    description: "Beautiful charts built with Recharts.",
    whenToUse: "Use for plotted data such as lines, bars, and areas. For single headline numbers use stat-card; for grouped KPIs use metric-panels." },
  { slug: "stat-card", name: "Stat Card", category: "Data Viz & Metrics",
    description: "KPI card with trend indicator and optional icon.",
    whenToUse: "Use for a single KPI with trend and optional icon. For several KPIs in a row use metric-panels; for plotted trends use chart." },
  { slug: "metric-panels", name: "Metric Panels", category: "Data Viz & Metrics",
    description: "Composed metric panels for KPI rows, usage dashboards, quota tracking, and trend summaries.",
    whenToUse: "Use for composed KPI rows, usage dashboards, and quota tracking. For one metric use stat-card." },
  { slug: "l1-distribution-bar", name: "L1 Distribution Bar", category: "Data Viz & Metrics",
    description: "Segmented bar showing Experience, Workflow, Integration, Foundation split.",
    whenToUse: "Use for the segmented Experience/Workflow/Integration/Foundation split. For generic linear progress use progress." },
  { slug: "health-indicator", name: "Health Indicator", category: "Data Viz & Metrics",
    description: "Semantic status icon for healthy, warning, or error states.",
    whenToUse: "Use for a semantic healthy/warning/error status icon. For lifecycle states use status-badge; for a checklist row use readiness-item." },
  { slug: "stepper-counter", name: "Stepper Counter", category: "Data Viz & Metrics",
    description: "Inline stage progress counter with mini progress bar.",
    whenToUse: "Use for an inline stage X of Y counter with a mini bar. For a full step flow use stepper; for a plain bar use progress." },
  { slug: "readiness-item", name: "Readiness Item", category: "Data Viz & Metrics",
    description: "Display-only checklist row with pass, warning, or fail status.",
    whenToUse: "Use for a display-only pass/warning/fail checklist row. For an interactive review row use review-checklist-row; for a single icon use health-indicator." },
  { slug: "activity-feed", name: "Activity Feed", category: "Data Viz & Metrics",
    description: "Chronological list of user actions with avatars.",
    whenToUse: "Use for a chronological list of user actions with avatars. For an approval or event sequence use timeline." },
  { slug: "timeline", name: "Timeline", category: "Data Viz & Metrics",
    description: "Vertical approval or event timeline with status indicators.",
    whenToUse: "Use for a vertical approval or event sequence with status. For general recent activity use activity-feed; for process steps use stepper." },

  // Planning
  { slug: "stepper", name: "Stepper", category: "Planning",
    description: "Multi-step progress indicator with horizontal/vertical orientation and dots, numbered, or icon variants.",
    variants: ["dots","numbered","icons"],
    whenToUse: "Use for multi-step process indicators. For an inline X of Y counter use stepper-counter; for project schedules use gantt." },
  { slug: "sortable", name: "Sortable", category: "Planning",
    description: "Reorderable list or grid pattern with accessible move controls.",
    whenToUse: "Use when users need to reprioritize work, reorder sections, or tune checklist sequence. For status-column movement use kanban-board." },
  { slug: "kanban-board", name: "Kanban Board", category: "Planning",
    description: "Drag-and-drop Kanban board with column management.",
    whenToUse: "Use for drag-and-drop columns of work items. For a time-phased schedule use gantt; for tabular work use data-table." },
  { slug: "gantt", name: "Gantt", category: "Planning",
    description: "Gantt timeline chart for project phase planning.",
    whenToUse: "Use for time-phased project schedules across columns or months. For status columns use kanban-board." },

  // AI Features
  { slug: "ai-action-bar", name: "AI Action Bar", category: "AI Features",
    description: "Subtle action strip with Sparkles icon and AI-powered action links.",
    whenToUse: "Use for a subtle strip of AI-powered action links. For a single AI suggestion use ai-suggestion-card." },
  { slug: "ai-draft-state", name: "AI Draft State", category: "AI Features",
    description: "Three-state badge strip for AI Draft → Reviewed → Approved flow.",
    whenToUse: "Use for the AI Draft → Reviewed → Approved status strip. For generic states use status-badge." },
  { slug: "ai-suggestion-card", name: "AI Suggestion Card", category: "AI Features",
    description: "Compact card for AI suggestions with Apply and Dismiss actions.",
    whenToUse: "Use for a compact AI suggestion with Apply and Dismiss. For a row of AI actions use ai-action-bar." },

  // Blocks & Patterns
  { slug: "section-document-card", name: "Section Document Card", category: "Blocks & Patterns",
    description: "Document section card with status badge, edit button, and AI action bar.",
    whenToUse: "Use for an editable document section with status and AI actions. Composes card, status-badge, and ai-action-bar." },
  { slug: "l1-component-card", name: "L1 Component Card", category: "Blocks & Patterns",
    description: "Domain model card for an L1 solution component with health and epics.",
    whenToUse: "Use to present an L1 solution component with health and epic counts on the domain board." },
  { slug: "epic-card", name: "Epic Card", category: "Blocks & Patterns",
    description: "Kanban card for an epic with ID chip, status badge, and conflict indicator.",
    whenToUse: "Use as a Kanban card for an epic with ID, status, and conflict cues. Place inside kanban-board." },
  { slug: "phase-column-header", name: "Phase Column Header", category: "Blocks & Patterns",
    description: "Kanban column header with stats and L1 distribution bar.",
    whenToUse: "Use as a Kanban column header with stats and the L1 distribution bar. Pairs with epic-card." },
  { slug: "risk-heatmap", name: "Risk Heatmap", category: "Blocks & Patterns",
    description: "3×3 likelihood × impact grid with colour-coded risk cells.",
    whenToUse: "Use for the 3×3 likelihood × impact risk grid. For single risk status use status-badge." },
  { slug: "open-question-row", name: "Open Question Row", category: "Blocks & Patterns",
    description: "Full-width row for open questions with linked items and action buttons.",
    whenToUse: "Use for a full-width open-question row with linked items and actions. For checklist rows use review-checklist-row." },
  { slug: "approval-workflow-card", name: "Approval Workflow Card", category: "Blocks & Patterns",
    description: "Card embedding an approval timeline with Approve/Request Changes buttons.",
    whenToUse: "Use for an approval flow with Approve and Request Changes. Embeds timeline." },
  { slug: "review-checklist-row", name: "Review Checklist Row", category: "Blocks & Patterns",
    description: "Checklist row with status icon, reviewer avatar, and status dropdown.",
    whenToUse: "Use for an interactive review row with reviewer avatar and status dropdown. For display-only use readiness-item." },
  { slug: "output-card", name: "Output Card", category: "Blocks & Patterns",
    description: "Document output card with format badge, readiness checklist, and action buttons.",
    whenToUse: "Use for a document output with format badge and readiness checklist. Composes readiness-item." },
  { slug: "intake-snapshot-card", name: "Intake Snapshot Card", category: "Blocks & Patterns",
    description: "Compact summary card for intake data with KV pairs and system tags.",
    whenToUse: "Use for a compact intake summary of key-value pairs and system tags." },
  { slug: "estimation-rollup-tree", name: "Estimation Roll-Up Tree", category: "Blocks & Patterns",
    description: "Collapsible tree table showing Phase → L1 → L2 → L3 estimate roll-up.",
    whenToUse: "Use for the collapsible Phase → L1 → L2 → L3 estimate roll-up. For per-story detail use estimate-detail-drawer." },
  { slug: "estimate-detail-drawer", name: "Estimate Detail Drawer", category: "Blocks & Patterns",
    description: "Sheet drawer showing story estimate breakdown with expert override.",
    whenToUse: "Use for a story-level estimate breakdown with expert override. Opens from estimation-rollup-tree; built on sheet." },
  { slug: "reconciliation-panel", name: "Reconciliation Panel", category: "Blocks & Patterns",
    description: "Side-by-side top-down vs bottoms-up reconciliation with decision radio group.",
    whenToUse: "Use for side-by-side top-down vs bottoms-up reconciliation with a decision." },
  { slug: "team-roster-panel", name: "Team Roster Panel", category: "Blocks & Patterns",
    description: "Tabbed table showing client and Nymbl team roles with phase allocations.",
    whenToUse: "Use for tabbed client and Nymbl team roles with phase allocations." },
  { slug: "portfolio-pipeline-view", name: "Portfolio Pipeline View", category: "Blocks & Patterns",
    description: "Toggle between table and Kanban views for the engagement pipeline.",
    whenToUse: "Use to toggle the engagement pipeline between table and Kanban views." },
  { slug: "app-sidebar", name: "App Sidebar", category: "Blocks & Patterns",
    description: "Dark app and engagement sidebars for NOS product shells.",
    whenToUse: "Use as the dark app/engagement shell sidebar in NOS products. Always use this rather than building a custom sidebar." },
]

export const categories = [
  "Layout",
  "Typography",
  "Buttons & Actions",
  "Forms & Inputs",
  "Navigation",
  "Overlays",
  "Feedback",
  "Data Display",
  "Data Viz & Metrics",
  "Planning",
  "AI Features",
  "Blocks & Patterns",
]
